name: react-native-android-build-apk
on: [push]
jobs:
   install:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - name: install npm
        run: |
           npm install
   build-android:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Install
            run: npm install
          - name: Build Android Release
            run: cd android && ./gradlew assembleRelease
          - name: upload Artificat
            uses: actions/upload-artifact@v1
            with:
               name: app-release.apk
               path: android/app/build/outputs/apk/release
          
          
          
          
